import "./mywork.css";
import bhromano from "../images/bhromano.png";

import gallery from "../images/gallery.png";
import typinggame from "../images/typinggame.png";
import sassimg from "../images/sassimg.png";
import gallery2 from "../images/gallery2.png";

const Mywork = () => {
  return (
    <>
      <div className="work" id="work">
        <h2 className="title">EXAMPLES OF MY WORK</h2>
        <p className="wrk-para">
          Below you can see a few samples of the work I have done together with
          a short description of the project, it's requirements and a view of
          the project.<b> To see the live website, just press the image!</b>
          If you are interested in examinging the code for the project, feel
          free to check out my GitHub
        </p>

        <div class="row justify-content-around">
          <div class="col-4 ">
            <div className="content-1">
              <h3 className="project-name">BHROMANO</h3>
              <p className="project-dscrb">
                <b>Built on: HTML, CSS, Sass, Figma</b> <br />
                The website was created from scratch based on a design in Figma.
              </p>
              <a href=" https://tas-web-hos.s3.eu-north-1.amazonaws.com/Test-assingment/index.html">
                <img
                  src={bhromano}
                  alt="travel-website"
                  className="protfolio-img"
                />
              </a>
            </div>
          </div>
          <div class="col-4">
            <div className="content-1">
              <h3 className="project-name">EXPANDING_GALLERY</h3>
              <p className="project-dscrb">
                <b>Built on: HTML, CSS, Javascript</b> <br />
                The website is created to show the photo slides if you click on
                the photo it will expand..
              </p>
              <a href=" https://tas-web-hos.s3.eu-north-1.amazonaws.com/DOM-galleryexpanding/index.html">
                <img
                  src={gallery}
                  alt="flower-photos"
                  className="protfolio-img"
                />
              </a>
            </div>
          </div>
          <div class="col-4">
            <div className="content-1">
              <h3 className="project-name">TYPING-GAME</h3>
              <p className="project-dscrb">
                <b>Built on: HTML, CSS,React.js ,Random word API </b>
                The game is build to check the typing speed skills .every 10
                seconds new word will be generated by the help of API.
              </p>
              <a href="https://tasneemth-test.000webhostapp.com/">
                <img src={typinggame} alt="game" className="protfolio-img" />
              </a>
            </div>
          </div>
        </div>
        <div class="row justify-content-evenly">
          <div class="col-4">
            <div className="content-1">
              <h3 className="project-name">Genesis</h3>
              <p className="project-dscrb">
                <b>Built on: HTML, CSS, Sass, Figma </b> <br />
                The project links between three separate pages it was a good
                practice for making separate pages of a site . and how to use
                flexbox and grids in the most optimal ways in order for the site
                to look good
              </p>
              <a href=" https://tas-web-hos.s3.eu-north-1.amazonaws.com/sass-assignment/index.html">
                <img
                  src={sassimg}
                  alt="genesis-webside"
                  className="protfolio-img"
                />
              </a>
            </div>
          </div>
          <div class="col-4">
            <div className="content-1">
              <h3 className="project-name">Gallery-APP</h3>
              <p className="project-dscrb">
                <b>Built on: HTML, CSS, React.js ,Random-Image API </b>
                <br />
                Gallery app were you can add or remove the images .every time
                add button is clicked random image generated from an API
              </p>
              <a href=" http://tas-web-hos.s3-website.eu-north-1.amazonaws.com/">
                <img
                  src={gallery2}
                  alt="winter-photos"
                  className="protfolio-img"
                />
              </a>
            </div>
          </div>
        </div>
      </div>
     
      <hr className="line" />
    </>
  );
};

export default Mywork;
